src/librehatti/catalog/urls.py
"""
urls of catalog are..
"""
from django.conf.urls import url, patterns

from django.views.generic import TemplateView


"""
urls showing the list of item purchased and redirects to page of adding 
new categories of product 
"""
urlpatterns = patterns('librehatti.catalog.views',
    url(r'^$', 'index'),
    url(r'^select_sub_category/', 'select_sub_category'),
    url(r'^jsreverse/', 'jsreverse'),
    url(r'^select_item/', 'select_item'), 
    url(r'^bill_cal/','bill_cal'),
    url(r'^list_products/','list_products'),
    url(r'^previous_value/','previous_value'),
    url(r'^order_added_success/','order_added_success'),
    url(r'^change_request/','change_request'),
    url(r'^price_per_unit/','price_per_unit'),
    url(r'^select_type/','select_type'),
)


urlpatterns += patterns('librehatti.catalog.request_change',
   url(r'^request_save/','request_save'),
   url(r'^list_requests/','list_request'),
   url(r'^view_request/','view_request'),
   url(r'^accept_request/','accept_request'),
   url(r'^reject_request/','reject_request'),
   url(r'^permission_denied/','permission_denied'),
)

src/librehatti/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from reports.register_generator import GenerateRegister
from reports.search import SearchResult
from ajax_select import urls as ajax_select_urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'librehatti.catalog.views.index'),
    url(r'^catalog/', include('librehatti.catalog.urls')),
    url(r'^useraccounts/', include('useraccounts.urls')),
    url(r'^print/', include('librehatti.prints.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/','librehatti.reports.views.search_form'),
    url(r'^search_result/', SearchResult.as_view()),
    url(r'^save_fields', 'librehatti.reports.views.save_fields'),
    url(r'^list_saved_registers', 'librehatti.reports.views.list_saved_registers'),
    url(r'daily_result', 'librehatti.reports.register.daily_report_result', name='daily_report_result'),
    url(r'consultancy_funds_report', 'librehatti.reports.register.consultancy_funds_report', name='consultancy_funds_report'),    
    url(r'tds_report', 'librehatti.reports.register.tds_report_result', name='tds_report_result'),    
    url(r'payment_report', 'librehatti.reports.register.payment_register', name='payment_register'),
    url(r'suspense_clearance_register', 'librehatti.reports.register.suspense_clearance_register'),
    url(r'servicetax', 'librehatti.reports.register.servicetax_register'),
    url(r'^main_register', 'librehatti.reports.register.main_register', name='main_register'),
    url(r'^proforma_register', 'librehatti.reports.register.proforma_register'),
    url(r'^non_payment_register', 'librehatti.reports.register.non_payment_register'),
    url(r'^client_register', 'librehatti.reports.register.client_register', name='client_register'),
    url(r'^lab_report', 'librehatti.reports.register.lab_report'),
    url(r'^suspense_register', 'librehatti.reports.register.suspense_register'),
    url(r'^tada_form', 'librehatti.reports.register.tada_form'),
    url(r'^tada_register', 'librehatti.reports.register.tada_register'),
    url(r'^tada_staff', 'librehatti.reports.register.tada_staff'),
    url(r'^tadastaffregister', 'librehatti.reports.register.tadastaffregister'),
    url(r'^tada_member', 'librehatti.reports.register.tada_member'),
    url(r'^org_form', 'librehatti.reports.register.org_form'),
    url(r'^org_charges', 'librehatti.reports.register.org_charges'),    
    url(r'^filter_sub_category/', 'librehatti.reports.views.filter_sub_category'),
    url(r'^bill/', 'librehatti.prints.views.bill'),
    url(r'^suspense_bill/', 'librehatti.prints.views.suspense_bill'),
    url(r'^quoted_bill/', 'librehatti.prints.views.quoted_bill'),
    url(r'^tax/', 'librehatti.prints.views.tax'),
    url(r'^bills/', include('librehatti.bills.urls')),
    url(r'^suspense/', include('librehatti.suspense.urls')),
    url(r'^generate_register/', GenerateRegister.as_view(), name='view_register'),
    url(r'^history/','librehatti.reports.previous_history.history'),
    url(r'^details/','librehatti.reports.previous_history.details'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^voucher/', include('librehatti.voucher.urls')),
    url(r'^receipt/', 'librehatti.prints.views.receipt'),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^programmeletter/', 'librehatti.programmeletter.views.programmeletter'),
    url(r'^programmerletter_details/', 'librehatti.programmeletter.views.programmerletter_details'),
    url(r'^programmerletter_details/', 'librehatti.programmeletter.views.programmerletter_details'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

try:
    from django.conf.urls import url, patterns
except:
    from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

src/librehatti/catalog/models.py
"""
models of catalog are..
"""
from django.db import models

from django.forms import ModelForm

import useraccounts

from django.contrib.auth.models import User

from django.http import HttpResponse

from mptt.models import MPTTModel, TreeForeignKey

import mptt.fields

from django.core.exceptions import ValidationError

import datetime

from tinymce.models import HTMLField

from librehatti.config import _BUYER
from librehatti.config import _DELIVERY_ADDRESS
from librehatti.config import _IS_DEBIT
from librehatti.config import _PURCHASED_ITEMS
from librehatti.config import _QTY
from librehatti.config import _REFERENCE
from librehatti.config import _REFERENCE_DATE

"""
This class defines the name of category and parent category of product
"""
class mCategory(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', blank=True, null=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return unicode(self.name)


class Unit(models.Model):
    unit = models.CharField(max_length=100)
    def __unicode__(self):
        return '%s' % (self.unit)


class Category(MPTTModel):
    name = models.CharField(max_length=100)
    parent = TreeForeignKey('self', null=True, blank=True, \
        related_name="children")
    unit = models.ForeignKey(Unit, null=True, blank=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    def __unicode__(self):
        return '%s' % self.name


"""
This class defines the name of product, category, price of eact item of
that product and the organisation with which user deals
"""
class Product(models.Model):
    name = models.CharField(max_length=100)
    category = mptt.fields.TreeForeignKey(Category, related_name="products")
    price_per_unit = models.IntegerField(blank=True,null=True)
    organisation = models.ForeignKey('useraccounts.AdminOrganisations')
    def __unicode__(self):
        return self.name


"""
This class defines the features of product
"""
class Attributes(models.Model):
    name = models.CharField(max_length=200)
    is_number = models.BooleanField(default = True)
    is_string = models.BooleanField(default = False)

    class Meta:
        verbose_name_plural = "Attributes"

    def __unicode__(self):
        return self.name


"""
This class defines the details about user, its organisation, along with
total discount and payment of job, and mode of payment
"""
class ModeOfPayment(models.Model):
    method = models.CharField(max_length=25)

    class Meta:
        verbose_name_plural = "Modes of payment"

    def __unicode__(self):
        return self.method


"""
This class defines the type of taxes, value, validation of taxes
mentioning the startdate and end date
"""
class Surcharge(models.Model):
    tax_name = models.CharField(max_length=200)
    value = models.FloatField()
    taxes_included = models.BooleanField(default = False)
    tax_effected_from = models.DateField(null = True)
    tax_valid_till = models.DateField(null = True)
    Remark = models.CharField(max_length=1000, null = True)
    def __unicode__(self):
         return self.tax_name


class PurchaseOrder(models.Model):
    buyer = models.ForeignKey(User,verbose_name= _BUYER)
    is_debit = models.BooleanField(default = False, verbose_name = _IS_DEBIT)
    reference = models.CharField(max_length=200, verbose_name=_REFERENCE)
    reference_date = models.DateField(blank=True, null=True, verbose_name=_REFERENCE_DATE)
    delivery_address = models.CharField(max_length=500, blank=True, null=True,\
        verbose_name = _DELIVERY_ADDRESS)
    organisation = models.ForeignKey('useraccounts.AdminOrganisations', default=1)
    date_time = models.DateField(auto_now_add=True)
    purchase_order_time = models.TimeField(auto_now_add=True)
    total_discount = models.IntegerField(default = 0)
    tds = models.IntegerField(default = 0)
    mode_of_payment = models.ForeignKey(ModeOfPayment)
    cheque_dd_number = models.CharField(max_length=50, blank=True)
    cheque_dd_date = models.DateField(max_length=50, blank=True, null=True)
    type_of_service = models.ForeignKey('useraccounts.OrganisationType')
    is_active = models.BooleanField(default = True)
    def save(self, *args, **kwargs):

        surchages = Surcharge.objects.filter(taxes_included=1)

        if surchages:
            pass
        else:
            raise ValidationError('No Active Taxes. Unable to add Order')
        from librehatti.voucher.models import FinancialSession
        now = datetime.datetime.now()
        financialsession = FinancialSession.objects.\
        values('id','session_start_date','session_end_date')
        for value in financialsession:
            start_date = value['session_start_date']
            end_date = value['session_end_date']
            if start_date <= now.date() <= end_date:
                session_id = value['id']
        try:
            session_id
            super(PurchaseOrder, self).save(*args, **kwargs)
        except:
            raise ValidationError('No Current Financial Session')
    def __unicode__(self):
        return '%s' % (self.id)


class PurchasedItem(models.Model):
    purchase_order = models.ForeignKey(PurchaseOrder)
    price_per_unit = models.IntegerField()
    qty = models.IntegerField(verbose_name = _QTY)
    price = models.IntegerField()
    item = models.ForeignKey(Product)
    def save(self, *args, **kwargs):
        try:
            if self.purchase_order:
                self.price = self.price_per_unit * self.qty
                super(PurchasedItem, self).save(*args, **kwargs)
        except:
            raise ValidationError('No Active Taxes. Unable to add Items')

    def __unicode__(self):
        return '%s' % (self.item) + ' - ' '%s' % (self.purchase_order)

    class Meta:
        verbose_name = _PURCHASED_ITEMS
        verbose_name_plural = _PURCHASED_ITEMS


"""
This class defines the features, value of product
"""
class Catalog(models.Model):
    attribute = models.ForeignKey(Attributes)
    value = models.CharField(max_length=200)
    product = models.ForeignKey(Product)
    def __unicode__(self):
        return self.attribute.name

"""
This class defines the taxes applied on the purchase order
"""
class TaxesApplied(models.Model):
    purchase_order = models.ForeignKey(PurchaseOrder)
    surcharge = models.ForeignKey(Surcharge)
    tax = models.IntegerField()
    def __unicode__(self):
        return "%s" % (self.surcharge)


"""
This class defines the grand total of the purchase order
"""
class Bill(models.Model):
    purchase_order = models.ForeignKey(PurchaseOrder)
    delivery_charges = models.IntegerField()
    total_cost = models.IntegerField()
    totalplusdelivery = models.IntegerField()
    total_tax = models.IntegerField()
    grand_total = models.IntegerField()
    amount_received = models.IntegerField()


class HeaderFooter(models.Model):
    header = HTMLField()
    footer = HTMLField()
    is_active = models.BooleanField(default = False)
    def save(self, *args, **kwargs):
        if self.is_active == True:
            temp = HeaderFooter.objects.filter(is_active=1)
            if temp:
                HeaderFooter.objects.filter(is_active=1).\
                update(is_active=0)
                super(HeaderFooter, self).save(*args, **kwargs)
            else:
                super(HeaderFooter, self).save(*args, **kwargs)
        else:
            super(HeaderFooter, self).save(*args, **kwargs)
    def __unicode__(self):
        return '%s' % (self.id)

    class Meta:
        verbose_name_plural = "Header and Footer"


class SurchargePaid(models.Model):
    surcharge = models.ForeignKey(Surcharge)
    value = models.IntegerField()
    date = models.DateField(auto_now_add = True)
    def __unicode__(self):
        return '%s paid on ' % (self.surcharge, self.date)


class ChangeRequest(models.Model):
    purchase_order_of_session = models.IntegerField()
    from librehatti.voucher.models import FinancialSession
    session = models.ForeignKey(FinancialSession)
    previous_total = models.IntegerField()
    new_total = models.IntegerField()
    description = models.CharField(max_length=100)
    initiator = models.CharField(max_length=50)
    initiation_date = models.DateField(auto_now_add = True)


class RequestSurchargeChange(models.Model):
    change_request = models.ForeignKey(ChangeRequest)
    surcharge = models.ForeignKey(TaxesApplied)
    previous_value = models.IntegerField()
    new_value = models.IntegerField()


class RequestStatus(models.Model):
    change_request = models.ForeignKey(ChangeRequest)
    confirmed = models.BooleanField(default=False)
    cancelled = models.BooleanField(default=False)
    request_response = models.DateField(null = True)


class NonPaymentOrder(models.Model):
    buyer = models.ForeignKey(User,verbose_name= _BUYER)
    reference = models.CharField(max_length=200, verbose_name=_REFERENCE)
    reference_date = models.DateField(verbose_name=_REFERENCE_DATE)
    date = models.DateField(auto_now_add=True)
    delivery_address = models.CharField(max_length=500, blank=True, null=True,\
        verbose_name = _DELIVERY_ADDRESS)
    item_type = models.CharField(max_length = 200)
    def __unicode__(self):
        return '%s' % (self.id)

src/librehatti/reports/models.py
from django.db import models

class SavedRegisters(models.Model):
	title = models.CharField(max_length = 200)
	selected_fields = models.CharField(max_length = 1000)

	def __unicode__(self):
		return self.title

src/librehatti/bills/forms.py
from django import forms

from librehatti.bills.models import *

from librehatti.catalog.models import ModeOfPayment, Category, Product
from librehatti.catalog.models import PurchaseOrder

import itertools

from ajax_select import make_ajax_field

from librehatti.config import _PARENT_CATEGORY
from librehatti.config import _SUB_CATEGORY
from librehatti.config import _ITEM
from librehatti.config import _TYPE


class BuyerForm(forms.ModelForm):
    buyer = make_ajax_field(QuotedOrder, 'buyer', 'buyer')

    class Meta:
        model = QuotedOrder
        exclude = ('is_active',)

    class Media:
        js = (
            'js/hide_add_buyer.js',
            'http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js',
            'js/cheque_dd_date.js',
            )


"""
This form lets user to select item after categories are filtered in dropdown.
"""
class ItemSelectForm(forms.ModelForm):
    class Media:
        js = (
            'http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js',
            'js/quote_ajax.js',
            'js/quoted_price_per_unit.js',
        )

    try:
        parent_category = forms.ModelChoiceField(queryset=Category.objects.\
            filter(parent__parent__isnull=True).\
            filter(parent__isnull=False), label=_PARENT_CATEGORY)
        sub_category = forms.ModelChoiceField(queryset=Category.\
            objects.all(), label=_SUB_CATEGORY)
    except:
        pass

    item = forms.ModelChoiceField\
    (queryset = Product.objects.all(), label = _ITEM)
    CHOICES = (('', '---------',), ('1', 'Lab Work',), ('2', 'Field Work',))
    type = forms.ChoiceField(choices=CHOICES, label = _TYPE)
    price_per_unit = forms.IntegerField()

    def __init__(self, *args, **kwargs):
         super(ItemSelectForm, self).__init__(*args, **kwargs)
         self.fields['type'].widget.attrs={'class': 'type'}
         self.fields['parent_category'].widget.\
         attrs = {'class':'parent_category'}
         self.fields['sub_category'].widget.attrs = {'class':'sub_category'}
         self.fields['item'].widget.attrs = {'class':'item'}
         self.fields['price_per_unit'].widget.\
         attrs = {'class':'quoted_price_per_unit'}


class SelectNoteForm(forms.Form):
    quoted_order = forms.CharField(widget=forms.\
        TextInput(attrs={'readonly':'readonly'}))
    note_line = forms.ModelMultipleChoiceField(widget=forms.\
        CheckboxSelectMultiple(attrs={'class':'note_checkbox'}),\
        queryset=NoteLine.objects.filter(is_permanent=0))

src/templates/autocompleteselect.html
<span id="{{ html_id }}_wrapper">
    <input type="text" name="{{name}}_text" id="{{html_id}}_text" value="" autocomplete="off" {{ extra_attrs }} />
    {% if add_link %}
    <a href="{{ add_link }}" class="add-another addlink" id="add_{{ html_id }}" onclick="return showAddAnotherPopup(this);"> add</a>
    {% endif %}
    <input type="hidden" name="{{name}}" id="{{html_id}}" value="{{current_id}}" data-ajax-select="autocompleteselect" data-plugin-options="{{ data_plugin_options }}" />
    <div id="{{html_id}}_on_deck" class="results_on_deck"><div>{{current_repr|safe}}</div></div>
    {% block extra_script %}{% endblock %}
    {% block help %}{% if help_text %}<p class="help">{{help_text}}</p>{% endif %}{% endblock %}
</span>

src/templates/base.html
{% load i18n %} {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    {% block extrahead %}
    <script type="text/javascript">
        var reverseurl = "{% url 'librehatti.catalog.views.jsreverse' %}";

        function reverse(urlstring, callback) {
            if (typeof callback != "function") {
                return false;
            }
            
            $.get(reverseurl + "?string=" + urlstring, callback);
        }
    </script>
    {% endblock %}
    {% block js %}
    <script src='http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'>
    </script>
    <script src="{% static 'js/jquery-ui.min.js' %}">
    </script>
    <script src="{% static 'js/bootstrap-timepicker.min.js' %}">
    </script>
</script>
<script src="{% static 'js/total.js' %}">
</script>
<script src="{% static 'js/quoted_save_distance.js' %}">
</script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap-dialog.js' %}"></script>
<script src="{% static 'js/note_save_delete.js' %}">
</script>
<script src="{% static 'js/accordion.js' %}">
</script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.voucher').attr('disabled', 'disabled');
        $('.material').attr('disabled', 'disabled');
        $('.adddistancesave').attr('disabled', 'disabled');
        $('.add_distance').change(function(event){
            voucher_no = event.target.id.split("_")[1];
            distance = $('#distance_' + voucher_no).val();
            order = $('#order').val();
            reverse('librehatti.suspense.views.save_distance', function(url) {
                var request_url = url + "/?voucher=" + voucher_no + "&distance=" + distance + "&order=" + order;
                $.ajax({
                    url: request_url,
                    success: function(data){
                    }
                });
            });
        });
    })
</script>
<script type="text/javascript">
    $(document).ready(function(){
    $('#add_distance_div').dblclick(function(){
        $('.adddistancesave').removeAttr('disabled');
    });
})
</script>
<script type="text/javascript">
        $(document).ready(function(){
    $('#button1').click(function(){
        $('#button1').attr('disabled', 'disabled');
    })
});
</script>
<script type="text/javascript">
    $(document).ready(function(){
        $('#id_sub_category').attr('disabled', 'disabled');
        $('#id_parent_category').change(function(){
            $('#id_sub_category').empty();
            $('#id_sub_category').removeAttr('disabled');
            parent_id = $(this).val();
            reverse('librehatti.reports.views.filter_sub_category', function(url) {
                var request_url = url + "?parent_id=" + parent_id;
                $.ajax({
                    url: request_url,
                    datatype: 'json',
                    success: function(data){
                        $.each(JSON.parse(data), function(key,value) {
                            $('#id_sub_category').append('<option value="' + key + '">' + value + '</option>');
                        });
                    }
                })
            });
        })
    });
    $(function() {
        $('#id_start_date').datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        })
        $('#id_start_date').datepicker( "option", "showAnim", "clip" )
        $('#id_end_date').datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        })
        $('#id_end_date').datepicker( "option", "showAnim", "clip" )
        .datepicker('widget').wrap('<div class="ll-skin-lugo"/>');
        $('#id_date').datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        })
        $('#id_start_test_date').datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        })
        $('#id_end_test_date').datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        })
        $('#id_Date_of_generation').datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        })
        $('#id_clear_date').datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        })
    $('#id_departure_time_from_tcc').timepicker({
    defaultTime: 'value',
    minuteStep: 1,
    disableFocus: true,
    template: 'dropdown',
    showMeridian:false
});
    $('#id_arrival_time_at_site').timepicker({
    defaultTime: 'value',
    minuteStep: 1,
    disableFocus: true,
    template: 'dropdown',
    showMeridian:false
});
    $('#id_departure_time_from_site').timepicker({
    defaultTime: 'value',
    minuteStep: 1,
    disableFocus: true,
    template: 'dropdown',
    showMeridian:false
});
    $('#id_arrival_time_at_tcc').timepicker({
    defaultTime: 'value',
    minuteStep: 1,
    disableFocus: true,
    template: 'dropdown',
    showMeridian:false
}); 
});       
</script>
{% endblock js %}
{% block extrajs %} {% endblock extrajs %}
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-timepicker.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/list_result.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bill.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/accordion.css' %}">
{% block extracss %} {% endblock extracss %}

</head>
<body>
    <div class = "wrapper">
        <div class="white-board">
            <div class ="main-box" id="c-panel"> 
                <header class="primary-branding">
                   <a href='/'> <span class="pb-dark">LIBRE</span><span class="pb-light">HATTI</span></a>
               </header>
               {% block content %}{% endblock %}
           </div>
           <div class ="account">
            <nav id="primary_nav_wrap">
                <ul>
                  <li>
                    {% if request == 1 %}
                    <a href="#"><img width="40px" src="{% static 'icons/Settings-1.png' %}"></a>
                    {% else %}
                    <a href="#"><img width="40px" src="{% static 'icons/settings.png' %}"></a>
                    {% endif %}
                    <ul>
                      <li><a href='{% url 'librehatti.catalog.request_change.list_request' %}'>View requests</a></li>
                      <li><a href="{% url 'admin:index' %}">Admin panel</a></li>
                      <li><a href="{% url 'admin:password_change' %}">Change Password</a></li>
                      <li><a href="{% url 'admin:logout' %}">Log out</a></li>
                  </ul>
              </li>
          </ul>
      </nav>
  </div>
</div>
</div>

src/templates/bill_base.html
{% load i18n %} {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bill.css' %}">
    <style>
        body{
            font-size:1.3em;
        }
    </style>
</head>
<body>
<div class='main_header'>
    {{header.header | safe}}
<hr>
</div>
<div class='logo'>                                                    
 <img src='{{STATIC_URL}}/css/images/logo.png'   
 class=".img-responsive">                                             
 </div>
    <div class = "bill-wrapper">
        {% block content %}{% endblock %}
    </div>
    {{footer.footer | safe}} 
    {% block extracontent %}
    {% endblock %}
</body>
</html>

src/templates/catalog.html
{% extends base_template|default:"base.html" %} {% load i18n %} {% block content %} {% if nocategory %}
<div class="text-center">
    <h1>No Categories. Please add some Categories</h1>
    <a href="{% url 'admin:index' %}" class="btn btn-primary btn-large">Add Category</a>
</div>
{% else %}
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            {% if noproducts %}
            <h1>No Products. Please add some.</h1>
            <a href="{% url 'admin:index' %}" class="btn btn-large btn-primary">Add Products</a>
            {% endif %}
            <div class="row clearfix">
                {% for product in productlist %}
                <div class="col-md-3 column well ui-widget-content draggable product" id="{{ product.id }}product">
                    <input type="checkbox" />
                    <span>{{ product.name }}</span>
                    <button class="btn btn-xs btn-primary">Add to Cart</button>
                </div>
                {% endfor %}
            </div>
            <div class="droppable">
            </div>
        </div>
    </div>
</div>
<div id="cart" class="cart">
    <ul id="cartitems">
    </ul>
</div>
<script type="text/javascript">

    //This function will be used to add itrms in the cart. Only one piece 
    $(".product button").click(function() {

    //First read the id of the product
    var parent = parseInt($(this).parent("div")[0].id);    

    // We have the product id. Get the name show
    var name = $(this).siblings("span").html();
    cart.addItem(name, parent, 1);
});

    //This will make the element draggable
    $(".draggable").draggable();
    
    //This will make it droppable
    $(".droppable").droppable({

    });
</script>
{% endif %} {% endblock %}

src/templates/error_page.html
{% extends "error_base.html" %}
{% load i18n %}

{% block title %}{{type}}{% endblock %}

{% block error %}{% trans 'error'|capfirst %} 404{% endblock %}

{% block content %}
  {{message}}
{% endblock %}